mode = "dark"

accent = "#add7ff"
selection = "#3d484d"
selection_foreground = "#f8f8f2"
selection_background = "#2a2e3f"
muted = "#6c6f93"

background = "#1b1e28"
dark_background = "#1b1e28"
darker_background = "#1b1e28"
lighter_background = "#252B37"

foreground = "#a6accd"
dark_foreground = "#a6accd"
light_foreground = "#ffffff"
bright_foreground = "#e4f0fb"

red = "#d0679d"
yellow = "#fffac2"
orange = "#fffac2"
green = "#5de4c7"
cyan = "#add7ff"
blue = "#89ddff"
magenta = "#d2a6ff"

bright_red = "#d0679d"
bright_yellow = "#fffac2"
bright_green = "#5de4c7"
bright_cyan = "#add7ff"
bright_blue = "#89ddff"
bright_magenta = "#d2a6ff"
