$color = rgba(26,27,38,1.0)
$font_color = rgba(205,214,244,1.0)
$font_family = Geist Mono

input-field {
  monitor =
  size = 440, 60
  position = 0, -440
  halign = center
  valign = center

  inner_color = rgba(26,27,38,0.0)
  outer_color = rgba(205,214,244,0.0)
  outline_thickness = 2

  font_family = $font_family
  font_color = $font_color

  dots_size = 0.2
  dots_spacing = 0.4

  placeholder_text = Enter Password
  check_color = rgba(68,157,171,1.0)
  fail_text = $FAIL <b>($ATTEMPTS)</b>

  rounding = 0
  shadow_passes = 0
  fade_on_empty = false
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%k:%M")"
  color = $font_color
  font_size = 96
  font_family = $font_family
  position = 0, 320
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = $font_color
  font_size = 18
  font_family = $font_family
  position = 0, 220
  halign = center
  valign = center
}
